export const TITULAR = {
	token: '',
	selectedSexo: '',
	domainSexo: [],
	selectedEstadoCivil: '',
	domainEstadoCivil: [],
	selectedOperadora: null,
	domainOperadora: [],
	selectedDataNascimento: null,
	selectedTemPlanoSaude: '',
	selectedTemOdonto: '',
	domainPlanos: [],
	domainPlanosOdonto: [],
	tipoDependente: [],
	selectedTipoDependente: '',
	selectedPlano: null,
	loading: false,
	url_imagem: '',
	selectedOperadoraOutroBeneificio: null,
	selectedBeneficio: null,
	cargo: '',
	aceitoPagar: 101,
	regime: '',
	steps: ['Dados do Titular', 'Dependentes', 'Concluído'],
	nome: '',
	email: '',
	whatsapp: '',
	cpf: '',
	rg: '',
	// email: '',
	dataNascimento: null,
	idade: '',
	nomeMae: '',
	dataAdmissao: null,
	peso: '',
	altura: '',
	cep: '',
	endereco: '',
	bairro: '',
	cidade: '',
	erroMessage: '',

	resposta_1: 101,
	pergunta_1: '',
	esclarecimento_1: '',
	resposta_2: 101,
	pergunta_2: '',
	esclarecimento_2: '',
	resposta_3: 101,
	pergunta_3: '',
	esclarecimento_3: '',
	resposta_4: 101,
	pergunta_4: '',
	esclarecimento_4: '',
	resposta_5: 101,
	pergunta_5: '',
	esclarecimento_5: '',
	resposta_6: 101,
	pergunta_6: '',
	esclarecimento_6: '',
	resposta_7: 101,
	pergunta_7: '',
	esclarecimento_7: '',
	resposta_8: 101,
	pergunta_8: '',
	esclarecimento_8: '',
	resposta_9: 101,
	pergunta_9: '',
	esclarecimento_9: '',
	pdfPlano: null,

	solicitacao_empresa: '',
	id_solicitacao: 0,
	showSuccess: false,
	showError: false,

	selectedStep: 0,
	openModal: false,

	outroBeneficio: 101,
	domainBeneficios: [],
	termoAceito: 101,
	seguroVida: 101,

	dependente_cpf: '',
	dependente_rg: '',
	dependente_nome: '',
	dependente_nome_mae: '',
	dependente_peso: '',
	dependente_altura: '',

	loadingInicial: true,

	arrayDependentes: [],
	concluido: false,

	mensagemOdonto: '',
	valorAdicionalOdonto: '',
	termoAceiteOdonto: 101,
};
